apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: litlink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-container
        image: ghcr.io/spehic/users:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "40m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
        
        startupProbe:
          httpGet:
            path: /v1/users/readiness       # Readiness check endpoint
            port: 8080
          initialDelaySeconds: 60  # Delay before first probe
          periodSeconds: 10        # Check every 10 seconds
          failureThreshold: 30     # After 30 failures, consider the pod as failed
          successThreshold: 1      # 1 successful probe is enough to consider pod as started
          timeoutSeconds: 10        # Timeout after 5 seconds

        livenessProbe:
          httpGet:
            path: /v1/users/healthz         # Liveness check endpoint
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 5
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /v1/users/readiness       # Readiness check endpoint
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: litlink
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

