kumuluzee:
  name: litlink
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/LitLinkDS
    connection-url: jdbc:postgresql://postgres:5432/litlink
    username: postgres
    password: postgres
    max-pool-size: 20
