kumuluzee:
  name: litlink
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 9095
  datasources:
    - jndi-name: jdbc/LitLinkDS
      connection-url: jdbc:postgresql://localhost:5432/litlink
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/LitLinkDS
  
